#
# This source file is part of the CardinalKit open source project
#
# SPDX-FileCopyrightText: 2022 Paul Schmiedmayer <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  desc "Build app"
  lane :build do
    cocoapods(
      podfile: "./CardinalKit-Example/"
    )
    build_app(
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Publish a beta release to internal TestFlight testers"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
    increment_build_number({
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "CardinalKit-Example/CardinalKit.xcodeproj"
    })
    cocoapods(
      podfile: "./CardinalKit-Example/"
    )
    disable_automatic_code_signing(
      path: "CardinalKit-Example/Pods/Pods.xcodeproj",
      team_id: ENV["TEAM_ID"],
      code_sign_identity: "Apple Distribution"
    )
    # build_app
    # upload_to_testflight
  end
end
