use_frameworks!

target 'CardinalKit_Example' do
  pod 'CardinalKit', :path => '../'
  
  # CK Sample Pods
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'stable'
  
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Storage'

  target 'CardinalKit_Tests' do
    inherit! :search_paths

    # Pod recommended, & testing
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
